# Generated by Django 3.0 on 2019-12-31 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wordsearch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='word_pdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordsearch.PDFStorage')),
                ('word_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordsearch.Words')),
            ],
        ),
    ]
